#!/bin/sh

if [ "$#" -ne 1 ] ; then
  echo "Usage: $0 [ch571|ch573|ch581|ch582|ch583]" >&2
  exit 1
fi

#fix Link.ld linebreak
sed -i "s/\r/\r\n/g" Ld/Link.ld

# collect sources and asms.
find . -type f -name "*.c"|sed 's@^\./@@g;s@$@ \\@g' > c_source.list
find . -name \*.S|sed 's@^\./@@g;s@$@ \\@g'|head -n 1 > startup_asm_source.list

sed "s/C_SOURCE_LIST/$(sed -e 's/[\&/]/\\&/g' -e 's/$/\\n/' c_source.list | tr -d '\n')/" Makefile.ble.ch5xx.template >Makefile
sed -i "s/STARTUP_ASM_SOURCE_LIST/$(sed -e 's/[\&/]/\\&/g' -e 's/$/\\n/' startup_asm_source.list | tr -d '\n'|head -n 1)/" Makefile

rm -f c_source.list startup_asm_source.list

if [ $1"x" = "ch571""x" ]; then
	sed -i "s/target/ch571/g" Makefile
	sed -i "s/5xx/573/g" Makefile
fi

if [ $1"x" = "ch573""x" ]; then
	sed -i "s/target/ch573/g" Makefile
	sed -i "s/5xx/573/g" Makefile
fi

if [ $1"x" = "ch581""x" ]; then
	sed -i "s/target/ch581/g" Makefile
	sed -i "s/5xx/583/g" Makefile
fi

if [ $1"x" = "ch582""x" ]; then
	sed -i "s/target/ch582/g" Makefile
	sed -i "s/5xx/583/g" Makefile
fi

if [ $1"x" = "ch583""x" ]; then
	sed -i "s/target/ch583/g" Makefile
	sed -i "s/5xx/583/g" Makefile
fi


